# Generated by Django 4.2.3 on 2023-07-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('publication_year', models.IntegerField()),
                ('cover_image_url', models.CharField(max_length=200)),
                ('ebook_link', models.CharField(max_length=200)),
            ],
        ),
    ]
